from hypothesis import given, strategies as st
"""
James - HW 3 Question at top of .py script

discuss the differences between the inputs generated by hypothesis 
and what you would expect from the other approaches that we've covered.

Answer: hypothesis compared to other testing cases will randomly 
select from generated cases it produces that can include edge 
cases, all of which can be more complex than what 
I or other people could think of for testing purposes.

Compared to what other approaches that we've covered which are based on what I've
done in the Roman converter, TCAS, and mutations assignments where I found graphs (Like in the TCAS)
of if/else blocks, for roman converter I would try to find easy, but also extreme (Depends on each person) cases
to test them out to see if it works for possibly all cases, though not complete coverage is possible
For mutation that is more simple than hypothesis in which it just will randomly mutate the logic of the code
somewhat to to see the quality of inputs by changing something small about it rather than generating them like hypothesis.
"""

# Base Strategy: digits and constants
# constant = digit {digit}
# Using map(str) ensures that we work with strings rather than integers
constant = st.integers(min_value=0, max_value=999).map(str)

@st.composite
def factor(draw):
    """
    factor = constant | "(" expression ")"
    """
    # Randomly decide if we go deeper into a nested expression or stay at a constant
    if draw(st.booleans()):
        # We use deferred() to reference 'expression' before it is fully defined
        nested_expr = draw(st.deferred(expression))
        return f"({nested_expr})"
    return draw(constant)

@st.composite
def term(draw):
    """
    term = factor { ("*" | "/") factor }
    """
    # Start with at least one factor
    result = draw(factor())
    # Generate a list of (operator, factor) pairs to simulate the { ... } repetition
    # max_size=2 helps keep the generated strings readable
    extra_factors = draw(st.lists(
        st.tuples(st.sampled_from(["*", "/"]), factor()), 
        max_size=2
    ))
    
    for op, next_f in extra_factors:
        result = f"{result} {op} {next_f}"
    return result

@st.composite
def expression(draw):
    """
    expression = term { ("+" | "-") term }
    """
    result = draw(term())
    
    # Similarly, simulate the repetition of terms
    extra_terms = draw(st.lists(
        st.tuples(st.sampled_from(["+", "-"]), term()), 
        max_size=2
    ))
    
    for op, next_t in extra_terms:
        result = f"{result} {op} {next_t}"
    return result

def expr():
    return expression()

@given(expr())
def test_print(expr: str):
    """
    Hypothesis will call this multiple times with different generated strings.
    """
    print(expr)
    assert isinstance(expr, str)
